### ISSUE TITLE
READMG subset string includes garbage.

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#118]
The subset string returned from the ireadmg seems to include garbage which can not be removed with the Fortran trim command. Using the Fortran len or trim_len to determine the actual size of the subset string does not work either. The problem occurs for me in Fortran 90 when giving the ireadmg function a character array which is larger than the resulting subset string.

```fortran
character(len=25) :: f_subset     !! 25 cause I figured that was long enough to hold any subset name
ires = ireadmg(bufr_unit, f_subset, iddate)
```
I got back the following in f_subset:
MSTTB001\020\271\265\362\271U\000\000\000\000\000\000\000\000\000\000P

**Comment by rmclaren** [comment]
Here's some code to reproduce the problem:

```fortran
program bufr_test
    use bufr_file

    character(25) subset
    integer :: idate
    integer(kind=8) :: iret
    integer :: lunit

    call open_bufr("/home/rmclaren/Work/ioda-bundle/ioda_converters/test/testinput/gnssro_kompsat5_20180415_00Z.bufr")

    lunit = 12
    do while (ireadmg(lunit, subset, idate) == 0)
        do while (ireadsb(lunit) == 0)
            print *, trim(subset)
        end do
    end do
end program
```

**Comment by rmclaren** [comment]
Please take a look at my original comment in #108

**Comment by jbathegit** [comment]
Inside of ireadmg, the subset variable is explicitly declared as character*8.  So the maximum length of any subset identifier is 8 characters, and the function is designed to always return exactly 8 characters, left-justified with blank fill to the right if the subset identifier is less than 8 characters.  But this also means that you should never expect any valid content in characters 9 to len(str) when str is longer than 8.

**Comment by rmclaren** [comment]
If this is true you should probably check the input and make sure the supplied character array is always exactly 8 characters (crash if it is not) as this will almost certainly result in unintended behavior.

**Comment by jbathegit** [comment]
Not sure if that's necessarily a good solution, b/c I've seen application codes written in C which call readmg with a 9-character string, and then after the return they explicitly set the 9th character to a trailing null so the string can then be treated like a C string.  In my opinion, users should be allowed to pass in any size string they want, and based on the fact that the parameter is explicitly defined as character*8 in the documentation, they should understand that this means they should never expect anything useful to be returned in the characters beyond the 8th character.

Again, just my $0.02, and I realize that the API for many of the Fortran routines should probably be modified at some point to utilize more modern/standard ways of interfacing with C code.  We already have two related open issues (#20 and #79) on that topic, and you've also provided a very helpful prototype with your bufr_interface API, which is much appreciated.  So maybe just a matter of one of us finding the time to really dive into this and expand upon your earlier work.  I certainly support anything that modernizes the library and makes it useful to as wide an audience as possible, so long as we maintain backwards-compatibility for our many existing users.  And that's why I've been advocating for one or more modern API layers on top of the existing code, rather than a wholesale rewrite of the entire library.
