### ISSUE TITLE
[improvement] manual test data download

### ISSUE THREAD

**Issue by nuitlejour** [NOAA-EMC/NCEPLIBS-bufr#150]
during make step, process 'stuck' at 100% without showing any message, after a little digging around, I found it's downloading 239M test file bufr-11.6.0.tar. 
it is possible to setup an option to choose the test file when I already downloaded manually?

**Comment by nuitlejour** [comment]
[update] you can manually copy bufr-11.6.0.tar to test folder, make process will skip download this test data.

**Comment by edwardhartnett** [comment]
OK, but it should still work if we don't do that...

**Comment by nuitlejour** [comment]
thank you for the tip, my internet connection is very unstable, it takes about 10 minutes to download the test data, adding an download prompt will be nice.

**Comment by edwardhartnett** [comment]
The way this should work is for the download script to look for the test files, if not found, they should be downloaded. If found, no download needs to happen.

**Comment by GeorgeVandenberghe-NOAA** [comment]
Ed, I just ran into this on Jet which does not have curl connectivity to EMC.   Bufr doesn't build and I needed (maybe still need) Rahul's help to find that test data issue)  I take a little different tack.. Download-only=Y in the stack configuration should download this and it doesn't because the test data download happens in the build, not the repository clone.

**Comment by GeorgeVandenberghe-NOAA** [comment]
I got bufr to build BTW by getting rid of the test section in test/CMakelists..txt.  Wgrib2 has the download issue and I suspect DOWNLOAD ONLY on another machine, will rectify that.   I jump on stack failure to build issues because I am always afraid someone will ask me to build it on some machine out in the internet sticks with a weird configuration to support some rapidly escalating management priority

**Comment by GeorgeVandenberghe-NOAA** [comment]
The way it works now is the bufr build fails and that stops the hpc-stack build.  It's not the fault of hpc-stack.  The manual fix is to go to the hpc-stack pkg/buf*/build/test directory and get bufr.tar to it somehow.  I just got an offline copy from hera and copied it.   Once this is done go to ../ and type make and make will proceed with the test and the bufr build will complete.  Meanwhile back in hpc-stack, all of the builds prior to and including bufr should be removed from stack/stack.noaa.yaml or whatever it's using to configure, then rerun the stack build and it should go the rest of the way.   There isn't any way to do a clean hpc-stack build with this problem  on a machine without connectivity so yes this needs to be fixed.

**Comment by edwardhartnett** [comment]
Lets add an extra target, extra_test, which will require the downloaded files. The test target will only run tests that don't depend on any data file. That way we can still run the tests in our CI, but hpc-stack will not be bothered with them...

**Comment by GeorgeVandenberghe-NOAA** [comment]
This sounds good.   It's a general issue in builds that require additional connectivity to complete the build which defeats downloading what's needed on well connected machine A and transferring the stuff to machine B which has blocked connectivity to repositories or other external sites.
