### ISSUE TITLE
Count the number of messages in BUFR file and then read all messages into internal array

### ISSUE THREAD

**Issue by delick** [NOAA-EMC/NCEPLIBS-bufr#157]
Is there a function to count the total number of messages in a single BUFR file? I tried to open the bufr file, loop over messages to get the number first, but when I proceed to read all messages to memory using `ufbmem`, a segmentation error occured:

```bash
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

in `Main.F90`
```fortran
use utils        ! Import subroutine
! ...
! Count the number of meesages using loop.
CALL countMessage(bufr_file,nmessage)
print *, 'Total # of messages: ', nmessage
open(unit_in,file=bufr_file,form='unformatted',status='old')

! Read BUFR messages into internal array.
print *, 'Reading messages to internal array'
call ufbmem(unit_in, 1, iret, iunit)
```

in `utils.F90`
```fortran
! Open BUFR file.
open(unit_in,file=file_name,form='unformatted',status='old')
CALL openbf(unit_in, 'IN', unit_in)

! Count in message loop.
num_message = 0
message_loop: do while(ireadmg(unit_in, subset1, idate1) == 0)
    num_message = num_message + 1
end do message_loop

! Close BUFR file.
CALL closbf(unit_in)
CLOSE(unit_in)
```

**Comment by jbathegit** [comment]
I can only speculate here without seeing more details about the SIGSEGV, but here are a couple of things I noticed:

1. Some systems require a rewind before attempting to open and read the same file a second time within the same run of an application program.  Maybe try adding a `rewind(unit_in)` statement prior to the second `open` statement?
2. I see you're calling `ufbmem` with the 2nd argument set to a value of 1, and which in turn means that presumably you've already called `ufbmem` somewhere else in your code to store messages from another file into the internal arrays.  Otherwise, if this is your first call to `ufbmem`, then you should set the 2nd argument to a value of 0.

By the way, if all you really want to know is how many messages are in the file, then there's really no need to do an initial loop through the file with `ireadmg`.  Instead, you could remove all of that extra code and just call `ufbmem` with the 2nd argument set to a value of 0, and the return value of the 3rd argument (`iret` in your code) would tell you the exact same thing!

**Comment by jbathegit** [comment]
Closing this issue due to lack of further response from the user.
