### ISSUE TITLE
add support for multiple versions of the documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#183]
See https://github.com/NOAA-EMC/NCEPLIBS-g2c/issues/126

**Comment by jbathegit** [comment]
Effective with today's commit of the documentation for v11.7.1, the `gh-pages` branch now contains a `previous_versions` subdirectory, which in turn contains subdirectories holding copies of the documentation for the previous versions `v11.5.0`, `v11.6.0`, and `v11.7.0`. 

I've gone ahead and edited the Release Notes links for each of these previous versions within [the Releases page](https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases), in order to now point each of them to the corresponding version of the documentation noted above.  The final step will be figuring out where it would be most appropriate to add these same links to prior versions of the documentation within each new version of the documentation itself, perhaps within the main `docs/user_guide.md` page(?)

Once that's done, we can then add this rotating of documentation versions to our SOP for new version releases, and then we can formally close this issue.

**Comment by jbathegit** [comment]
Or, maybe it would be sufficient (and easier to maintain going forward!) if we just added the following line to the second paragraph of `docs/user_guide.md`:

**For access to the full documentation of a prior version of this library, please see our [releases page](https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases), and then scroll down and click on the corresponding "Release Notes" link for that version.**

We could also add the same line to the second paragraph of `README.md`, so that users could access the documentation for older versions of the software from there as well.  And that way, we wouldn't have to update `docs/user_guide.md` (or `README.md`) within each successive version of the software; rather, we'd just need to update the links within [the Releases page](https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases), and users who wanted to see older versions of the documentation could access them that way(?)

Any other ideas or suggestions are welcome.
