### ISSUE TITLE
some missing code figures for T29 in local table and getcfmng.f not working for TYP=x NCNW=2 

### ISSUE THREAD

**Issue by jack-woollen** [NOAA-EMC/NCEPLIBS-bufr#211]
@jbathegit See below, what I get dumping T29 codes from prepbufr. Notice codes 524,525,526 are missing.
Also I don't think getcfmng is working for TYP codes even given NCNW qualifiers. I made a test code to check this on hera. 
See hera:/scratch1/NCEPDEV/global/Jack.Woollen/typtest/maketyp.

 11   80865   Fixed land RAOB and PIBAL by block and station number
 22     126   Ship RAOB with name
 31      61   Reconnaissance aircraft or dropwinsonde
 41  312146   Aircraft flight-level (all types)
 63  208461   Satellite derived winds
 72  365249   NEXRAD Vertical Azimuth Display (VAD) winds
 77    4285   NOAA Profiler Network (NPN) or Multi-Agency Profiler (MAP) R
511   62544   Land surface by block and station number (synoptic, both unr
512   91858   Land surface by call letters (METAR)
514    3874   Mobile land surface (synoptic)
522     900   Ship with name
523       2   Ship without name (report ID set to "SHIP")
524    9139
525     286
530   28995
531     718   C-MAN platform
534      12   Coast Guard tide gauge report
561    1275   Fixed buoy arriving in WMO TAC FM-13 format
562     243   Fixed or drifting buoy arriving in WMO TAC FM-18 format
563    6658   Fixed buoy arriving in WMO BUFR format
564    5787   Drifting buoy arriving in WMO BUFR format
584  120437   ASCAT scatterometer winds

**Comment by jbathegit** [comment]
I don't have an account on hera.  Could you put a copy of your test code somewhere on WCOSS or WCOSS2 so I can take a look at it there?

**Comment by jack-woollen** [comment]
I put the test code on wcoss2 in /lfs/h2/emc/global/noscrub/Jack.Woollen/typtest script maketyp. Thanks for looking at it.

**Comment by jbathegit** [comment]
There do seem to be some missing entries for T29 within bufrtab.CodeFlag_LOC_0_7_1, including the more recent entries in the 524-530 range.  I probably just need to regenerate that table from the database and then push it up to the repository.  However, I can't do that until Monday at the earliest, b/c I'm still waiting on the NCO folks to restore network access to my emc-lw7-jator workstation, which is where the database is housed.  So hopefully NLT Monday, and at that time I'll also check whether the LOC tables for TableB and TableD need to be regenerated as well.

As for TYP, that's just due to an error in your typtabl file; specifically, the correct FXY number for NCNW is 001225, not 001255.  If you fix that in your typtabl, and also change the name of the 7th argument in your 2nd call to getcfmng to be something other than "len" (which is a Fortran intrinisic), then it should work.  Maybe just reuse the name "lens" as in your 1st call to getcfmng?
