### ISSUE TITLE
update Doxyfile.in to doxygen-1.9.1

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#245]
Doxyfile.in contains setting for the doxygen build.

It needs to be updated from time to time with the ubuntu-latest doxygen release (currently 1.9.1).

Once updated we can use the WARN_AS_ERROR setting to cause doxygen warnings to fail CI. We will do this as a separate issue (see discussion below).

I will add this to #243

**Comment by jbathegit** [comment]
Hi @edwardhartnett.  I agree that Doxyfile.in should be updated from time to time to account for new settings in the doxygen software, so thanks for this!  I'm actually using v1.9.4 on my home desktop.

In principle, I also agree that doxygen warnings should be treated as CI fails.  However, in reality, doxygen warns for a lot of things that it shouldn't.  For example, it thinks the BUFR DX table notation `<PPWSQ1>` is an unsupported xml/html tag even when it's encapsulated inside of a `<pre>` block, so it then flags it with a warning when it really shouldn't, since anything inside of an HTML `<pre>` block is supposed to be treated as plain, preformatted text.  I've seen other warnings as well in the past which have left me scratching my head about how robust doxygen's parser really is, but I haven't had time yet to really dive in and try to figure out a way to get around all of them, nor have I had time yet to even add basic doxygen markup to every subprogram in the library.  So bottom line is that we're nowhere near ready to try and set WARN_AS_ERROR=YES.

**Comment by edwardhartnett** [comment]
In terms of the doxygen version, you want to use the same one as is used in ubuntu-latest (currently 1.9.1). (You can check the version at any time by adding a doxygen --version command to the workflow, or just googling.)

Mostly the version is pretty flexible, but the one time it matters is when doing the doxygen -u to update the Doxyfile. If you use 1.9.4 for this, it may add new parameters to the Doxyfile which will generate warnings on the 1.9.1 run the CI is using, and generate warnings, which will break the build. For me, hilarious confusion ensued until I realized what was going on. ;-)

I will separate the issue of updating the doxyfile from the issue of turning on WARN_AS_ERROR and other warning flags...

**Comment by edwardhartnett** [comment]
This was done and merged. I will close this issue.
