### ISSUE TITLE
Add documentation to all undocumented files, finish conversion of legacy documentation to doxygen (allowing us to turn on WARN_AS_ERROR in Doxyfile)

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#246]
I'm getting this documentation problem. I remember I've seen it before in other Fortran doxygen projects - not sure if I ever found a solution...

`Error in file /home/runner/work/NCEPLIBS-bufr/NCEPLIBS-bufr/bufr/build/utils/sinv.f90 line: 115, state: 22(String)`

Many files in NCEPLIBS-bufr are undocumented. This is a violation of best practices and NOAA coding standards.

**Comment by edwardhartnett** [comment]
It turns out that there is some documentation work that needs to be done in NCEPLIBS-bufr. See discussion in #245.

Documentation has been brought up to a pretty high standard in all the other (active) NCEPLIBS libraries. NCEPLIBS-bufr is one of the most important of the NCEPLIBS libraries, so we want the documentation to look and function at its best. 

The high-level documentation for NCEPLIBS-bufr looks good, and many of the modules and functions look very nice. But some of the code files have only been very roughly converted from the legacy all-caps documentation.

Unlike UFS_UTILS and some of the GRIB repos, NCEPLIBS-bufr never got the surge of documentation help from other team members. Let's correct that, so that NCEPLIBS-bufr can start the new year without a backlog of doxygen work, and with very nice-looking documentation for its next release.

@jbathegit I propose that some of the NCEPLIBS team step in to help get documentation up to a high-standard, as we have done on other NCEPLIBS repos.

The plan:
1. identify and develop one or more examples of good doxygen within the repo. This may take a few PRs to iterate.
2. List the files to be modified in this issue, and divide the work between @AlexanderRichert-NOAA, @Hang-Lei-NOAA , and myself. 
3. We will submit a series of PRs which will be documentation changes only - no code changes. Jeff, your role will be to review and fill in missing information, which we will indicate with a triple-question-mark "???".  When you see that, you need to tell us what should be there instead. 

Doxygen work, once understood, is straightforward and easy. If we each spend just a few hours a week on it, it will be done in no time. This work is very important, but not urgent, we can take our time. WCOSS2 or other operational issues should always take precedence.

What does everyone think?

**Comment by jbathegit** [comment]
Thanks, and this sounds great to me!

I do have quite a few Doxygen updates included in the `r8wraps` branch (which will resolve #78), because I've been updating docblocks in routines at the same time that I've been modifying them to handle either 4-byte or 8-byte integers.  So that will help some, and once that's merged I'll go ahead and set up a list of which files still need to be updated, along with a list of some good examples to follow.

As an FYI, @jack-woollen may(?) also be able to help with this task as well.  He's been invaluable in helping to resolve #78 and other important issues, so he would definitely be a big help, but I don't know what other projects he's tasked with at the moment so only question may be availability.

Thanks again, and just FYI that I will be tied up with a WMO meeting for most of next week, and I'm done for the year (use or lose leave) after the 20th, so no promises that this will get done before the new year, but the plan sounds good and I will do my part to get us there (eventually ;-)!

**Comment by jack-woollen** [comment]
@edwardhartnett @jbathegit Sounds good here too. I can definitely spend a few hours a week. Keep me in the loop.

**Comment by jbathegit** [comment]
The `r8wraps` branch has been merged along with some additional documentation tweaks to get rid of some other Doxygen warnings, so this is ready now for any and all help to get the remaining docblocks squared away.

The most up-to-date version of the documentation (based on the current status of the `develop` branch) is available at https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib_jeff/html_new/index.html  Just click on Files->FileList from the top menu bar, and then you can easily see which subroutines and functions still need Doxygen-style docblocks, because those will have blank content in the description line (otherwise, the contents of the \@brief tag would get displayed there!)

For the record, since #78 is now done, and before I work on any further documentation myself, I'm going to work on finishing up #79 so that we have a cleaner and more modern Fortran<->C interface.  I'm also going to work on adding another test code for some of the subroutines and functions which aren't currently being covered by the gcovr utility.

**Comment by edwardhartnett** [comment]
OK I will submit a PR today with just one or two changed files, and we can discuss...

**Comment by edwardhartnett** [comment]
The documentation for NCEPLIBS-bufr is poor. There are many undocumented files. This violates NOAA standards.

NOAA and the science community deserve professionally documented code.

**Comment by edwardhartnett** [comment]
OK, we are making good progress here.

If we keep this up, I believe we will be able to turn on Doxygen's WARN_AS_ERROR flag by the end of the week, which will be a big step forward for the documentation.

**Comment by jbathegit** [comment]
This is completed now with the merging of #310
