### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#255]
I think we can take a few iterations on the README to improve it a bit.

* We know the code authors, so lets list them. I have added @jack-woollen and @jbathegit . Who else wrote code?
* We would like to have a secondary code manager for this repo, so Jeff can take a vacation day occasionally. We could put me, or Hang, or Alex. That comes with a requirement that the secondary code manager maintain familiarity with the code, build, and CI system, so they can do an emergency release if necessary...
* I think we can reference some BUFR WMO docs, as we do the WMO GRIB docs from the GRIB repos.
* I don't think we should list supported compilers. In fact, all standard-conforming Fortran compiilers should work, with correct flags, and we do not officially support anything but Intel, right? So let's continue to support as many compilers as we think useful, and not specify them on the readme.
* Our build instructions should start with a GitHub release tarball, not a git clone.

Anything else anyone can think of?

**Comment by edwardhartnett** [comment]
Also I may have asked this before @jbathegit - have you guys ever done any conference papers or presentations about BUFR? If so, we can reference them in the README.

Also, are there any diagrams that are useful for understanding NCEPLIBS-bufr? We can include them in the README if so...

**Comment by jbathegit** [comment]
re: the official BUFR bible/reference (WMO Manual 306, Volume I.2), this is currently linked on the main page of the [User Guide](https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_jeffa_nceplibs_bufr_docs_UserGuide.html), but if you want to list it in the README file as well, then the link is https://library.wmo.int/index.php?lvl=notice_display&id=10684#.X68yu8hKiUn

re: not explicitly listing all of the supported compilers and/or having the build instructions reference a tarball instead of a clone, either or both of those are fine with me, though I'm not sure how you would have a user download a tarball that isn't tied to a particular release.  In other words, do we want the README instructions to always reference an explicit (i.e. the latest) release version number, so that we also have to update the README instructions every time we do a new release?    Or am I missing something here?

Either way, both of the above practices (listing all of the supported compilers, and referencing a clone) were just copied from other NCEPLIBS libraries back in the day, because they were considered best/standard practices at the time.  Again, it's fine with me if we want to now change this, and assuming the same approach is consistently adopted across all of the other libraries going forward.

**Comment by jbathegit** [comment]
And BTW, sorry but no we haven't presented at any conferences in the past or have any other library diagrams or presentation docs, at least not that I'm aware of.

**Comment by edwardhartnett** [comment]
WRT users, we DON"T want them going to github and building some in-between-releases version of NCEPLIBS-bufr. We want every NCEPLIBS-bufr install to come from a release tarball, so that we know exactly what the code is, and it has been properly documented, tested, and released.

So we ALWAYS want users to start from a released tarball, not from whatever today's GitHub clone happens to be.

**Comment by edwardhartnett** [comment]
WRT no papers about NCEPLIBS-bufr, I think it would be very helpful to have one. People like to cite a paper so it's good to have a canonical conference paper describing the library that anyone can reference. We should put one together for the AGU/AMS...
