### ISSUE TITLE
complete testing of ufbrw.f

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#362]

**Comment by jack-woollen** [comment]
@edwardhartnett  I made a branch called jsw_ufbrw_test as a place to start. I put the code in the utils directory because that's the simplest way to include in the cmake process. It probably belongs somewhere else but i'd like some guidance on that.  There's a script in test_scripts to run the test. It checks many of the possible operations in the ufbrw subroutine, both input and output.

**Comment by edwardhartnett** [comment]
Awesome! Can we remove the script and just have the test program do everything?

**Comment by jack-woollen** [comment]
Done. Might now be ready for prime time.

**Comment by edwardhartnett** [comment]
We have some decent testing for this subroutine (65% coverage) but there are some large untested error conditions. Can we reach these in a test? @jack-woollen what do you think?

**Comment by jack-woollen** [comment]
I think so. I'll work on it.
