### ISSUE TITLE
combine files bort.f, bort2.f, bort_exit.f, errwrt.f into error_handling.F90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#373]
I suggest we combine files bort.f, bort2.f, bort_exit.f, errwrt.f into one new F90 file called error_handling.F90.

This should only be done after we have tested all our error handling code.

Any other error handling subroutines should go in error_handling.F90, it should use free-format (i.e F90 style formatting and line continuation.)

All new error handling subroutines would then also go in this file.

**Comment by jbathegit** [comment]
FYI, bort_exit is a C (.c) code, not a Fortran (.f) code.

**Comment by edwardhartnett** [comment]
Actually why do we even have bort_exit()? We can just use stop and eliminate bort_exit(), right?

**Comment by edwardhartnett** [comment]
OK, the original question remains.

This code was written with one subroutine per file, because of the arcane rules of the computers back in ancient times.

Well these are modern times and we don't have to do that. Most fortran projects (outside NOAA) use files to organize subroutines and functions, and don't usually have one file per subroutine. Instead, the group subroutines of similar function into files.

For example the netcdf-fortran project has a file netcdf_attributes.F90 which contains all the attribute functions.

The advantage is just another version of Occam's razor - having less entities in the build system is useful and reduces complexity. 

@jbathegit what do you think?

**Comment by jbathegit** [comment]
I agree in principle with this, and in fact I've already done a bit of this sort of consolidation myself as part of some recent updates, and which in turn has cut down on the number of separate source files.

For example, see the latest version of cfe.c which now contains 7 related functions, crwbmg.c which now contains 5, and stseq.c which now contains 3.  So that was 15 separate source files consolidated down into 3, and yes there's much more that could still be done along those lines, but as I've noted elsewhere this hasn't been my top priority recently.  The above cases were just some low-hanging fruit that I was able to do while I was making separately-needed mods to those files anyway as part of the recent overhaul of the C-Fortran interface within the library (see #79).

**Comment by edwardhartnett** [comment]
Thanks, just wanted to see where we stood on this. I agree there is certainly no rush, but over time it would be great to consolidate related subprograms into files.

I will leave this issue open since I think this is an easy case of this.
