### ISSUE TITLE
do we need subroutine chekstab?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#394]
We have function chekstab:

```
C> This subroutine checks that an internal BUFR table
C> representation is self-consistent and fully defined. If any errors
C> are found, then an appropriate call is made to bufr archive library
C> subroutine bort().

```

Why do we have such a subroutine?

Who is expected to call it and what are they expected to do if there is an inconsistent table representation?

**Comment by jbathegit** [comment]
This routine is only ever expected to be called internally by makestab(), right before it builds or rebuilds the internal jump/link table based on DX table information for all logical units that are open to the software at that time.

So bottom line, a user isn't ever supposed to call this routine directly.  And it would be difficult to fully test from within run_test_bort.sh, though I suppose you could at least test the first bort error by passing in some random integer as LUN.  But short of figuring out a way to separately read an incomplete table into internal arrays, I don't see how we could easily test the other subsequent bort errors, because passing in a bogus LUN would always trigger the first one.

**Comment by edwardhartnett** [comment]
But makestab() is fully under our control, correct? So we should know if the internal tables are in a disordered state, because only library code ever changes them, right?

So it seems like this can be dispensed with entirely, and we can instead write good tests for makestab(), which ensure that it always does the correct thing. 

Or am I missing something?

**Comment by jbathegit** [comment]
Yes, makestab is fully under our control, but the internal arrays that chekstab is checking are filled in a different part of the library (by different routines), so it's still worth doing those sanity checks before trying to build the jump/link table inside of makestab.

That said, and in the interest of reducing the overall number of routines, we certainly could take the 10 or so lines of code from chekstab and embed them directly into makestab, then delete chekstab as a separate routine.  @jack-woollen do you have any concerns, or can you think of any reason why that may not be a good idea?

**Comment by jack-woollen** [comment]
Checkstab is checking user input, so the check should be made. And, I don't see why it should be in-lined in makestab.  I think it's useful to let it maintain its identify as an independent check..

**Comment by edwardhartnett** [comment]
OK, thanks for the answers...
