### ISSUE TITLE
buffer overflow possible with cread.c function crdbufr() - documentation bug?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#450]
The function crdbufr() takes these parameters:

```
 * @param nfile - File ID.
 * @param bufr - BUFR message.
 * @param mxwrd - Number of elements in bufr array; used by the
 * function to ensure that it doesn't overflow the array.

```
The third parameter is the number of elements allocated in the array.

However, the code writes two ints beyond the end of this number, in this code:

```
    bufr[nintrem + 1] = wkint[0];
    bufr[nintrem + 2] = wkint[1];

```
So for this code to work, I have to declare the data array 8 bytes larger than the message size (in test_c_cread.c):

```
    /* Allocate storage to read a BUFR message into. Without the +8
     * these buffers will be overflowed by the cdrbufr(). */
    if (!(msg = malloc(MSG_SIZE + 8)))
        return TEST_ERR;
    if (!(msg2 = malloc(MSG_SIZE + 8)))
        return TEST_ERR;

```        

This could also be seen as a documentation error. If I change the documentation to say that the size of the buffer has to be at least 8 bytes longer than the message, that would be better. And actually we could check that once we know the size of the message. (That is, we could check that we have enough room, instead of just overwriting memory).

**Comment by jbathegit** [comment]
I realize this may be confusing, but there's no overflow danger here.  First of all, note that bufr is an int array, not a char array, and so mxwrd is the max number of 4-byte integers needed to hold the message, not the max number of bytes.  You may already be aware of that, but I wanted to point that out just in case.

Secondly, note that the initial calculation of `nbytrem=iupbs01_f(wkint,"LENM")-8` doesn't include the first 8 bytes (i.e. the first 2 4-byte integers) of the BUFR message, because we've already read those in.  And therefore the subsequent calculation of `nintrem = nbytrem/nb` is always going to be at least 8 bytes (i.e. at least 2 4-byte integers) less than the total size of the BUFR message for that same reason.  I say "at least" because we're doing integer math here (discarding any remainder), so the value of nintrem may not include all of the 4-byte integers needed to contain the rest of the message.  In other words, there may be a remainder of up to 3 additional bytes (i.e. up to 1 additional 4-byte integer) of the message beyond that point.

So bottom line, the calculated value of nintrem will always be at least 2 and no more than 3 4-byte integers short of the number needed to contain the entire BUFR message.  That's why we have the subsequent `if (nintrem+3>mxwrd)` check to prevent any overflow, and note also that the subsequent fread statement is only reading in the next nintrem-1 integers starting into the memory address of bufr[2].  In other words, we're purposely reading one integer word less than the value of nintrem, because we want to read the last few bytes of the messages byte-by-byte (rather than integer-by-integer) so that we can easily check for the ending "7777" string.  And that number of remaining bytes is now exactly `nbytrem = nb + nbytrem%nb` (i.e. at least 4 bytes, but no more than 7 bytes depending on what the remainder was from the aforementioned integer math calculation).  And once those are all read in, they get stored in array members nintrem+1 and nintrem+2 of the bufr array.  But again, and as noted earlier, nintrem is always going to be at least 2 4-byte integers short of the actual size of the BUFR message, and we've already accounted for that in the calculations, so there's no danger that we're going to overflow anything here, and there's no need for an application code to allow 8 extra bytes in the allocated size of the bufr array.

I realize you really have to get down into the weeds to understand what's going on here, but I assure you that the code logic and documentation are correct as is.

**Comment by edwardhartnett** [comment]
When you find yourself typing a long explanation of your code into GitHub, it's better to instead check out the code and add to the documentation. It's important that not just you and I understand the code, but also future programmers, perhaps not yet hired, perhaps not yet even born! ;-)

So add the information to the documentation in the code, not to GitHub, so that it will be there for future programmers.

In this case, I have transferred some of your explanation to the comments in cread.c. Take a look and make sure I got things right.

However, the test still fails if I change it to:

```
    if (!(msg = malloc(MSG_SIZE)))
        return TEST_ERR;
    if (!(msg2 = malloc(MSG_SIZE)))
        return TEST_ERR;

```

and 

```
    if (crdbufr(0, msg, MSG_SIZE/sizeof(int)))
        return TEST_ERR;

```
In this case, it hits this if-condition:

```
    if (nintrem + 3 > mxwrd) {
        fsetpos(pb[nfile], &nxtpos);
        return -3;
    }

```
and the function ends with -3.

**Comment by edwardhartnett** [comment]
I believe there is a bug here, because when I use the function as documented, it fails. Only if I provide a very large number for the final argument does the function succeed.

**Comment by jbathegit** [comment]
OK, I'll take another look when I get a chance.

**Comment by jbathegit** [comment]
You were right, there was still a bug.  Specifically, if the max size passed in as the 3rd argument to crdbufr was the same as the message size to be read, **and** if that number also happened to be an exact multiple of sizeof(int), then crdbufr was still trying to write one additional integer beyond that point.  I've fixed it now along with your test_c_cread code, and I'll push them up as a new PR in a few minutes.

Thanks for setting up the test code to catch this!

**Comment by edwardhartnett** [comment]
Glad we found this and fixed it. That's exactly what the test code is for!

And having this as part of our automated testing ensures that this error will not reoccur.
