### ISSUE TITLE
Intermittent build problem: Error: Cannot rename module file ‘share_errstr.mod0’ to ‘share_errstr.mod’

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#477]
```
f951: Fatal Error: Cannot rename module file ‘share_errstr.mod0’ to ‘share_errstr.mod’: No such file or directory
1643
compilation terminated.
```

Sometimes I see this error. What is going on?

Renaming code files is almost always a bad idea in the build system. Why are we attempting to rename our mod files?

**Comment by jbathegit** [comment]
We're not actively renaming anything, at least not that I'm aware of.  I think where this comes from is in the test subdirectory, where there are multiple test programs each with their own individual `module Share_errstr` embedded within the code.  So my guess is that, when there are multiple make processes running to compile these test programs simultaneously, then they're somehow tripping over each other when they each create their own .mod file in the same subdirectory.

I've seen this quite a bit myself, and I usually just rerun the failed job and it clears itself up on the next run.  I suppose we could try consolidating all of the `module Share_errstr` instances down to a single separate file and figure out how to change CMakeLists.txt accordingly, or we could also just rename each one internally to `module Share_errstr_intest7`, `module Share_errstr_outtest10`, etc. and prevent them from tripping over each other that way.  Assuming that's what's really going on here, and assuming this is worth spending a lot of time trying to chase down since it works more often than it doesn't.  Thoughts?
