### ISSUE TITLE
wrong name for tarball

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#516]
I don't know how it happened but the 12.0.0 tarball is named: NCEPLIBS-bufr-bufr_v12.0.0.tar.gz 

Let's make sure the next release has the correct style of name: NCEPLIBS-bufr-12.0.0.tar.gz is what I expected.

I don;t believe we should change the 12.0.0 tarball, but make sure this is right for the next release.

@AlexanderRichert-NOAA for the current bufr release in spack we have:

    url = "https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/refs/tags/bufr_v11.5.0.tar.gz"

So this needs to be updated and also the new incorrect tarball name needs to be accomodated. I'm not sure how to do that, and perhaps we should fix the existing tarball name - what do you think Alex?

**Comment by jbathegit** [comment]
Actually, looking at https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases, this particular naming convention goes all the way back to the oldest release 11.4.0 on that page.  When downloaded, every one of them has the same naming convention `NCEPLIBS-bufr-bufr.vX.Y.Z.tar.gz`.  So this isn't unique to just the latest v12.0.0 release.

My guess is that Github may be automatically prefacing the repository name (in this case, `NCEPLIBS-bufr`) to the tarball name (which is `bufr.vX.Y.Z.tar.gz`).  Otherwise I'm not sure how it's ending up that way, because it's not something we're intentionally doing anywhere in our configuration.

**Comment by AlexanderRichert-NOAA** [comment]
Is it possible to retroactively tweak the names? In any case as far as the Spack recipe it's no problem to have different versions with different URLs/file names.

**Comment by edwardhartnett** [comment]
I would not retroactively tweak them, because who knows what has been built around them.

But it would be good if we could figure out what is going on, and, on the next release, transition to a more standard name. I'm not sure what is going on either...

**Comment by AlexanderRichert-NOAA** [comment]
It appears GitHub has no setting for the file names out side of what it does automatically with the tag name (e.g., bufr_v12.0.0). We could try a test release with, say, tag "v13.0.0" and see if that gives us what we want. Note that when editing a release, the instructions from GH suggest a 'vX.Y.Z' tag name convention.

For what it's worth, the latest release for instance can also be accessed at https://github.com/NOAA-EMC/NCEPLIBS-bufr/archive/bufr_v12.0.0/NCEPLIBS-bufr-*12.0.0*.tar.gz
I'm assuming that GitHub infers the 12.0.0 in the filename by extracting it from the tag name.

**Comment by edwardhartnett** [comment]
OK, so in future releases we should use the tag names to match the usual convention and the rest of the NCEPLIBS. Although this may be a bit of a pain when we transition, once done it will be easier and match every other release.
