### ISSUE TITLE
Need new release tag for c readlc extension.

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#521]
Unfortunately we will need a new release tag so that the readlc extension can be made available via the various software stacks. It could just be version 12.0.1 or something as the change is very minor.

Please see: https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519

**Comment by rmclaren** [comment]
Dependent Pull Requests
https://github.com/JCSDA-internal/ioda-converters/pull/1325
https://github.com/JCSDA-internal/ioda-converters/pull/1344

**Comment by jbathegit** [comment]
Noted, and I'll try to get to this soon, but right now I'm still struggling to get them to implement the previous 12.0.0 release onto WCOSS2.

In the meantime, are there any other extensions or tweaks you anticipate needing sooner rather than later and can go ahead and include now, just so we can minimize the proliferation of additional future tags?

**Comment by rmclaren** [comment]
I believe the WCOSS issue may be holding up some of my PR's as well..

I don't have any changes for NCEPLIB-bufr in the pipeline.

**Comment by edwardhartnett** [comment]
I think it's fine to do a new release, even if WCOSS is not yet using the 12.0.0 release.

Please don't use a tag - do an actual release.

The agile concept is that releases should be almost free. But keeping all tests working, and only accepting PRs that incrementally improve the repo, we should always be ready for release. With a streamlined release procedure, the release should only take a few minutes.

**Comment by jbathegit** [comment]
@edwardhartnett agreed, and I always do an actual release, but I also always tag the last commit that's part of that release so we can refer back to it if need be.  I don't see how those two things have to be mutually exclusive.

I'll try to get to this soon, and when I do I'll also make sure to just tag it as `v12.0.1` instead of `bufr_v12.0.1`, per #516
