### ISSUE TITLE
Python interface can't open WMO files?

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#564]
The python interface on NCEPLIB-bufr doesn't seem to be able to open WMO BUFR files...

**Comment by jbathegit** [comment]
The way this sort of thing works is that you have to call openbf with 'SEC3' as the 2nd argument, and which in turn tells the library to read a BUFR file according to the Section 3 data description and the WMO master tables, rather than expecting a DX table to be embedded in the front of the file.

But it looks like that was never included as an option in the \_init\_ subprogram; rather, it looks like that subprogram was only ever encoded for options 'IN', 'OUT', and 'APN' in the self._ioflag argument.  So I guess that would need to be added in order for that to work.

**Comment by rmclaren** [comment]
I think you are correct. This is probably a low priority issue.

**Comment by jbathegit** [comment]
OK, but if/when we ever add this feature, just FYI that we'll probably also need to introduce a Python interface for the Fortran mtinfo() subroutine as well.

**Comment by rmclaren** [comment]
This was fixed some time ago..
