### ISSUE TITLE
Missing GOES SATWND in prepbufr

### ISSUE THREAD

**Issue by Nuo-Chen** [NOAA-EMC/NCEPLIBS-bufr#597]
I was trying to create synthetic observation using NCEP PREPBUFR files as the template. Looking at the prepbufr data on July 15 and August 15 from year 2020 to year 2023 as sample data, I noticed the data void in satellite wind field in all these files over North and South Americas (possibly missing GOES-east/west). Satellite wind from August 2016 is complete.

![image](https://github.com/NOAA-EMC/NCEPLIBS-bufr/assets/45551704/c679f99b-fd38-434c-b922-da879e711491)

The data I used was from NCAR's RDA archive ds337.0 and they are downloaded from NCEP NOMADS server according to the dataset manager at NCAR. The NCAR staff also found the satellite wind is missing from the SATWND BUFR file (RDA ds351.0).

**Comment by jbathegit** [comment]
I don't think this is a library issue, but in any case I'm bringing @ilianagenkova in on the discussion since she heads our observational processing team which generates the satwnd and prepbufr files.

**Comment by ilianagenkova** [comment]
@Nuo-Chen, some years ago a decision was made to stop adding new data to SATWND in the **prepbufr** files  because the volume of global coverage winds continues to increase while the prepbufr file was meant to be a smaller size file. 
Please use the ***satwnd*bufr_d** files on NOMADS for the full satellite winds data set.

When you say "_The NCAR staff also found the satellite wind is missing from the SATWND BUFR file (RDA ds351.0)_" I don't know what RDA ds351.0 means.
In our archive the GOES winds are present for 2023 July and August. If you'd like the data for  just the dates you mentioned I could share these with you:

[clogin09 /lfs/h2/emc/obsproc/noscrub/iliana.genkova/TEMP_Nuo-Chen]$ sinv GDA/gfs.20230815/00/atmos/gfs.t00z.satwnd.tm00.bufr_d
003  METOP-1 (Metop-B         572  591                                                                                
056  METEOSAT 9            121735  207                                                                                
057  METEOSAT 10           153698  207                                                                                
174  Himawari-9            132314  000                                                                                
209  NOAA 18                  226  000                                                                                
223  NOAA 19                  443  000                                                                                
224  NPP                    12873  616                                                                                
225  NOAA 20                12015  616                                                                                
**270  GOES 16               876099  617                                                                                
272  GOES 18              2039878  617**                                                                                
471  INSAT 3D                9540  000                                                                                
473  INSAT 3DR              57724  000                                                                                
783  TERRA                    122  000                                                                                
784  AQUA                    4350  000                                                                                
854  Non-specific mix       28102  000                                                                                
                          3449691

[clogin09 /lfs/h2/emc/obsproc/noscrub/iliana.genkova/TEMP_Nuo-Chen]$ sinv GDA/gfs.20230715/00/atmos/gfs.t00z.satwnd.tm00.bufr_d
003  METOP-1 (Metop-B        8112  591                                                                                
005  METOP-3 (Metop-C        3003  591                                                                                
056  METEOSAT 9            141987  207                                                                                
057  METEOSAT 10           142865  207                                                                                
174  Himawari-9            140733  000                                                                                
206  NOAA 15                  312  000                                                                                
223  NOAA 19                  387  000                                                                                
224  NPP                    26325  616                                                                                
225  NOAA 20                19668  616                                                                                
**270  GOES 16               874105  617                                                                                
272  GOES 18              1886985  617**                                                                                
473  INSAT 3DR              73170  000                                                                                
854  Non-specific mix       30663  000                                                                                
                          3348315

**Comment by tcram** [comment]
Hi,
I manage the SATWND bufr_d archive at NCAR that @Nuo-Chen is referring to.  

Our BUFR decoder retrieves latitude and longitude from the Table B mnemonics CLAT and CLON, which as it turns out contain missing values for most satellite platforms.  I've updated our decoder to check for missing CLAT and CLON, and, if missing, use CLATH and CLONH instead. 

This issue can be closed now.

Tom

**Comment by ilianagenkova** [comment]
Tom, good move, as some providers (JMA, i.e. NC00504*) still use CLAT and CLON.
